# Base image with pnpm enabled
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=development
RUN corepack enable

# Development dependencies and setup
FROM base AS dev-env
COPY . /usr/src/
WORKDIR /usr/src
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm -r --prod=false install --frozen-lockfile

# App Dev Server
FROM dev-env AS app-dev
WORKDIR /usr/src/
EXPOSE 3000
CMD ["node", "run.js", "project:start", "--project", "app", "-s"] 

# Server Dev Environment
FROM dev-env AS server-dev
COPY ./packages/server /usr/src/packages/server
WORKDIR /usr/src/
EXPOSE 3000
CMD ["node", "run.js", "project:start", "--project", "server", "-s"] 
