version: '3.8'

services:

  app:
    container_name: app
    build: 
      context: .
      target: app-deployer
      dockerfile: Dockerfile.prod
    restart: always
    ports:
        - 3000:3000
  
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    networks:
      - biaplanner_link

  server:
    container_name: server
    build:
      context: .
      target: server-deployer
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 4000:3000
    env_file:
      - .env.prod
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - biaplanner_link 
    


networks:
  biaplanner_link:
    driver: bridge
