version: '3.8'

services:

  app:
    container_name: app
    build: 
      context: .
      target: app-dev
      dockerfile: Dockerfile.dev
    restart: always
    ports:
        - 3000:3000
    volumes:
      - ./packages/app/:/usr/src/packages/app/
      - ./packages/shared/:/usr/src/packages/shared/
      - /usr/src/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    networks:
      - biaplanner_link
    depends_on:
      - server
      - database
      - phpmyadmin

  server:
    container_name: server
    build:
      context: .
      target: server-dev
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:3000
    volumes:
      - ./packages/server/:/usr/src/packages/server/
      - ./packages/shared/:/usr/src/packages/shared/
      - /usr/src/node_modules
    env_file:
      - .env.prod
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - biaplanner_link
    depends_on:
      - database
      - phpmyadmin
    
  database:
    container_name:  database
    image: mysql:5.7
    restart: always
    env_file: 
      - ./.env.dev
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - biaplanner_link
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    restart: always
    env_file: 
      - ./.env.dev
    ports:
      - 8080:80
    volumes:
      - ./data/phpmyadmin.config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - data:/run/mysqld/
    networks:
      - biaplanner_link
    depends_on:
      - database

networks:
  biaplanner_link:
    driver: bridge

volumes:
  data:
