# Base image with pnpm enabled
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Development dependencies and setup
FROM base AS dev-env
COPY . /usr/src/
WORKDIR /usr/src
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

# App Dev Server
FROM dev-env AS app-dev
WORKDIR /usr/src/packages/app
EXPOSE 3000
CMD ["pnpm", "start"] 

# Server Dev Environment
FROM dev-env AS server-dev
COPY ./packages/server /usr/src/packages/server
WORKDIR /usr/src/packages/server
EXPOSE 3000
CMD ["npx", "nodemon", "-L", "--config", "nodemon.json"] 
