version: '3.8'

services:

  app:
    container_name: app
    build: 
      context: .
      target: app-deployer
      dockerfile: Dockerfile.prod
    restart: always
    ports:
        - 3000:3000
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
      - CHOKIDAR_INTERVAL=300
    stdin_open: true
    tty: true
    networks:
      - biaplanner_link
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      target: server-deployer
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    env_file:
      - .env.prod
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    stdin_open: true
    tty: true
    networks:
      - biaplanner_link 
    
  database:
    container_name:  database
    image: mysql:5.7
    restart: unless-stopped
    env_file: 
      - ./.env.prod
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - biaplanner_link

networks:
  biaplanner_link:
    driver: bridge
